### ISSUE TITLE
Vallex 350 SE DSD TECH SH-U11 USB to RS485 converter

### ISSUE THREAD

**Issue by thobrit** [pvainio/vallox-mqtt#1]
Hello, 
I have a Vallex 350 SE and am trying to start it in Homeassistant with this gateway. unfortunately I lack the knowledge. What do I have to do to get vallox-mqtt to work in Home assistant?
Homeassistant runs as a Proxmox VM. MQTT is already running. I have a DSD TECH SH-U11 USB to RS485 converter with FTDI FT232 chip. Can someone help me there?

**Comment by pvainio** [comment]
Hello,

Check the settings on https://github.com/pvainio/vallox-mqtt .   Release packages contain compiled binaries for common linux platforms, arm and amd64.

After configuring the serial device and mqtt broker environment variables you can start the binary and it should publish the vallox device to home assistant.

**Comment by thobrit** [comment]
Hello,

Thank you for your quick response.

Then I just need a start.sh script in Home Assistant without install go ?

 

My start.sh :

export SERIAL_DEVICE=/dev/ttyUSB0

export MQTT_URL=tcp://10.10.10.11:1883

export MQTT_USER=homeassistant

export MQTT_PASSWORD=homeassistant

export ENABLE_WRITE=true

export ENABLE_RAW=true

export DEBUG=true

 

./vallox-mqtt

 

 

 

 

Von: Pekka Vainio ***@***.***>
Gesendet: Montag, 27. Februar 2023 04:15
An: pvainio/vallox-mqtt ***@***.***>
Cc: thobrit ***@***.***>; Author ***@***.***>
Betreff: Re: [pvainio/vallox-mqtt] Vallex 350 SE DSD TECH SH-U11 USB to RS485
converter (Issue #1)

 

Hello,

Check the settings on https://github.com/pvainio/vallox-mqtt . Release packages
contain compiled binaries for common linux platforms, arm and amd64.

After configuring the serial device and mqtt broker environment variables you
can start the binary and it should publish the vallox device to home assistant.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.*Message ID: <pvainio/
***@***.***>

**Comment by thobrit** [comment]
Hello,

it runs on an ubuntu 20.04 vm.

But only if I specify the git clone vallox-mqtt and the following in start.sh:

 

cd /opt/vallox-mqtt/

go run main.go

 

with the parameter

.\vallox-mqtt

 

comes the message permission dinied.

 

[cid]

 

export SERIAL_DEVICE=/dev/ttyUSB0

export MQTT_URL=tcp://10.10.10.11:1883

export MQTT_USER=homeassistant

export MQTT_PASSWORD=homeassistant

export ENABLE_WRITE=true

export ENABLE_RAW=true

export DEBUG=true

 

#./vallox-mqtt

 

#cd /opt/vallox-mqtt/

#go run main.go

 

Von: Pekka Vainio ***@***.***>
Gesendet: Montag, 27. Februar 2023 04:15
An: pvainio/vallox-mqtt ***@***.***>
Cc: thobrit ***@***.***>; Author ***@***.***>
Betreff: Re: [pvainio/vallox-mqtt] Vallex 350 SE DSD TECH SH-U11 USB to RS485
converter (Issue #1)

 

Hello,

Check the settings on https://github.com/pvainio/vallox-mqtt . Release packages
contain compiled binaries for common linux platforms, arm and amd64.

After configuring the serial device and mqtt broker environment variables you
can start the binary and it should publish the vallox device to home assistant.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.*Message ID: <pvainio/
***@***.***>

**Comment by pvainio** [comment]
If you have go installed, you can do "go run main.go", but if you don't have go installed, you can use precompiled binaries from https://github.com/pvainio/vallox-mqtt/releases .

Is the permission denied message about running the command or opening the serial device?  So is it like
./vallox-mqtt: permission denied, which means you don't have permission to run the binary, and could try chmod a+x ./vallox-mqtt to give the permission to execute.

Or is the error like:
ERROR error opening Vallox device /tmp/foo: open /tmp/foo: permission denied, which means you need to give the user the access to the serial device.

**Comment by thobrit** [comment]
Thank you for the quick support.

Now it also runs in Homeassistant!

 

The fan levels work, temperature values ​​are not displayed, which is not so
bad at first.

 

I have not yet managed to autostart in Homeassistant. I tried it via a shell
command in an automation.

 

Thanks very much

 

Von: Pekka Vainio ***@***.***>
Gesendet: Montag, 27. Februar 2023 07:58
An: pvainio/vallox-mqtt ***@***.***>
Cc: thobrit ***@***.***>; Author ***@***.***>
Betreff: Re: [pvainio/vallox-mqtt] Vallex 350 SE DSD TECH SH-U11 USB to RS485
converter (Issue #1)

 

If you have go installed, you can do "go run main.go", but if you don't have go
installed, you can use precompiled binaries from https://github.com/pvainio/
vallox-mqtt/releases .

Is the permission denied message about running the command or opening the
serial device? So is it like
./vallox-mqtt: permission denied, which means you don't have permission to run
the binary, and could try chmod a+x ./vallox-mqtt to give the permission to
execute.

Or is the error like:
ERROR error opening Vallox device /tmp/foo: open /tmp/foo: permission denied,
which means you need to give the user the access to the serial device.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.*Message ID: <pvainio/
***@***.***>
