### ISSUE TITLE
Running two ventilation systems in parallel

### ISSUE THREAD

**Issue by Sprocket02** [pvainio/vallox-mqtt#2]
I have 2 ventilation systems running. For two independent apartments in the house. This use case is not supported, is it?

**Comment by pvainio** [comment]
> I have 2 ventilation systems running. For two independent apartments in the house. This use case is not supported, is it?

No, currently not.  If the two systems are completely independent, then I think adding support should be quite easy having own mqtt topics for each device.

**Comment by Sprocket02** [comment]
Thanks for the info. Yes, both systems are completely independent of each other. If you could extend the integration in this respect, I will offer myself as a tester.

**Comment by pvainio** [comment]
> Thanks for the info. Yes, both systems are completely independent of each other. If you could extend the integration in this respect, I will offer myself as a tester.

There is now initial support for running multiple devices.  For now you have to run own process for each device, but they can connect to the same mqtt (and Home Assistant).  You should set DEVICE_ID and DEVICE_NAME for each device separately.

**Comment by Sprocket02** [comment]
Many many thanks!!
