### ISSUE TITLE
No temperature info

### ISSUE THREAD

**Issue by karij22** [pvainio/vallox-mqtt#3]
Hi,
I have installed Vallox-Mqtt.  I have Vallox-Mqtt and mosquitto running in Raspberry, and Mqtt client running In my Linux PC. When i start all this. 6 entitys are imedistely discovered. I see status of fan, and i can adjust fan speed, but status of all  temperature sensors are "unavailable". I have different Vallox model (121). Could the problem be in this ?

**Comment by pvainio** [comment]
> Hi, I have installed Vallox-Mqtt. I have Vallox-Mqtt and mosquitto running in Raspberry, and Mqtt client running In my Linux PC. When i start all this. 6 entitys are imedistely discovered. I see status of fan, and i can adjust fan speed, but status of all temperature sensors are "unavailable". I have different Vallox model (121). Could the problem be in this ?

Most probably that is the reason.  Did some research and it looks like there is newer version of the protocol.  My device is quite old and is a bit different.  I'll cook a new version soon that should support the temperatures from the newer protocol.

**Comment by pvainio** [comment]
> Hi, I have installed Vallox-Mqtt. I have Vallox-Mqtt and mosquitto running in Raspberry, and Mqtt client running In my Linux PC. When i start all this. 6 entitys are imedistely discovered. I see status of fan, and i can adjust fan speed, but status of all temperature sensors are "unavailable". I have different Vallox model (121). Could the problem be in this ?

There is now a new release that might work for you.  With configuration NEW_PROTOCOL=true it reads temperatures from different registers, that might work.  Unfortunately cannot test this myself with my own old device.

**Comment by karij22** [comment]
I try, but no success... Could it help if i give access to my raspberry ?

**Comment by pvainio** [comment]
> I try, but no success... Could it help if i give access to my raspberry ?

Debug logs could help, if set set NEW_PROTOCOL=true and DEBUG=true and send the log/output?

**Comment by karij22** [comment]
Here it comes...


[logfile.txt](https://github.com/pvainio/vallox-mqtt/files/15137459/logfile.txt)

**Comment by pvainio** [comment]
The issue was closed, is it now ok?

From the logs it can be seen that it does publish the temps to vallox/temp/* topics, so that should be ok.  Also it has sent autodiscovery to HA and if the sensors are visible in HA it should also be ok.  Then issue might be that the mqtt for the vallox does not have permission to write to vallox/temp/* or ha mqtt user does not have permission to read those?

**Comment by pvainio** [comment]
Unintentionally reopened

**Comment by karij22** [comment]
And story continue... Hi, I had a little problems wit Mosquitto, but now, (at last), it work. So im`m back with this "main issue"
Now temperatures shown in MQTT client, also it noticed about fan speed changes, but the speed not shown. As i understand, there is no info coming from vallox. MQTT Explorer : 
![kuva](https://github.com/pvainio/vallox-mqtt/assets/155797873/6c768a67-7123-48be-a532-1497a630a51e)
Is there any possibilities that problem is not  in "my side"?

**Comment by pvainio** [comment]
> And story continue... Hi, I had a little problems wit Mosquitto, but now, (at last), it work. So im`m back with this "main issue" Now temperatures shown in MQTT client, also it noticed about fan speed changes, but the speed not shown. As i understand, there is no info coming from vallox. MQTT Explorer : ![kuva](https://private-user-images.githubusercontent.com/155797873/328005011-6c768a67-7123-48be-a532-1497a630a51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDA3MjYsIm5iZiI6MTcxNDkwMDQyNiwicGF0aCI6Ii8xNTU3OTc4NzMvMzI4MDA1MDExLTZjNzY4YTY3LTcxMjMtNDhiZS1hNTMyLTE0OTdhNjMwYTUxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwOTEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2I5ZDA1MmQ4ZGI4M2E3MDAzNjU2NGZlZDQzM2JjNGJlNTVhYmEyNWI5MGQwYjFiM2Q1YzE0NjM3NjM2NWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dLUGIDFtb_zEvhTsCIaZUZx-5ihOVAfMYjJkz5tQUzA) Is there any possibilities that problem is not in "my side"?

My device is quite lazy to publish fan speed to rs485 bus so it can take some minutes for it to appear.  Does it show the current speed after changing the speed?  After changing the speed my device reports the new speed to the bus.  If not, could you once again take the debug log when changing the speed to understand what happens on the rs485 bus.   Don't really know, but I guess there can be differences between different device models.  It might be that your device does not publish the values on its own and requires polling instead.

**Comment by karij22** [comment]
With OLD protool:































Hi, it doesn`t show speed after change. I have wait hours..
![kuva](https://github.com/pvainio/vallox-mqtt/assets/155797873/341812ff-bde4-46c8-b471-94a084a6815a)
[vallox_log.txt](https://github.com/pvainio/vallox-mqtt/files/15213180/vallox_log.txt)

**Comment by karij22** [comment]
Btw... I have also RH% and Co2 sensors. Should it show alse these ?

**Comment by pvainio** [comment]
> With OLD protool:
> 
> Hi, it doesn`t show speed after change. I have wait hours.. ![kuva](https://private-user-images.githubusercontent.com/155797873/328022552-341812ff-bde4-46c8-b471-94a084a6815a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjEwNzcsIm5iZiI6MTcxNDkyMDc3NywicGF0aCI6Ii8xNTU3OTc4NzMvMzI4MDIyNTUyLTM0MTgxMmZmLWJkZTQtNDZjOC1iNDcxLTk0YTA4NGE2ODE1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxNDUyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzBhNzllNDdhODg4NThhZDIzNTUzMTM5ZDViZWFkZWNiNTBiOWEwYWRmYTFjNTQ0NWI4YmYwMzE1MzNiMTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AuAWUwuVDlKnrwave2jo3p0gJjBQYfCU6N2H0yXITnU) [vallox_log.txt](https://github.com/pvainio/vallox-mqtt/files/15213180/vallox_log.txt)

This was a bug, the speed was not handled correctly the the new list of topics.  Should be fixed now within the new release.  Currently rh and co2 is not handled, since I don't have the sensors in my Vallox device, but should be easy to add.  I found some registers where to read those and will add them next.

**Comment by karij22** [comment]
Hi, thanks a lot. I can confirm, the other functions will already work in Vallox 121 SE model 3560 from year 2011 with "new protocol" setting
